### ISSUE TITLE
Need "carousel" block

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#11]
As included on Demos comp here: https://zpl.io/aNxjkj4

**Comment by mnyrop** [comment]
Hi @hadro, @glenrobson! Carousel implementation is ready to view here: https://preview.iiif.io/root/feature/demo-carousels-11/demos/ (YAML front-matter here: https://raw.githubusercontent.com/IIIF/website/feature/demo-carousels-11/source/demos/index.md)

Feel free to add any edit requests to this ticket & I'll add them to the PR.
