### ISSUE TITLE
Update markdown docs to use new root/api URL schemes

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#18]
Now that we've settled on the scheme for linking to internal URLs, we can go through and update copy links

**Comment by hadro** [comment]
Ok, I thought I had done this right, but had to revert because it broke all the links in the preview deployment.

The commit (which has since been rolled back) is here: https://github.com/IIIF/api/commit/9a54ca237fea0ff3299803b7cb128a1239e89606

When it deployed, it did not include the branch name in the preview URL. That causes all the links to 404.

So, for example, the Jekyll for the Image 3.0 spec before and after:

- `{{ site.url }}{{ site.baseurl }}/api/image/3.0/`
- `{{ site.api_url }}/image/3.0/`

And the resulting links:
- https://preview.iiif.io/api/wireframe/api/image/3.0/
- https://preview.iiif.io/api/image/3.0/

@glenrobson / @mnyrop is this something I screwed up in terms of updating the liquid variable links, or is this something that we need to adjust in terms of preview branch github actions?

**Comment by hadro** [comment]
I should add that running locally, all the links work, and it all passes the CI link check --  just when I pushed that the preview deployment had broken links.

**Comment by glenrobson** [comment]
I think its probably a build issue (github actions). I'm planning on trying to create a new branch with your commit above applied to try and debug.

**Comment by glenrobson** [comment]
I'm not sure if there is a better jekyllly way of doing this but its currently solved by adding the following line to the action:

```
run:  sed -i "s/^api_url:.*$/api_url:\t'\/api\/${{ env.BRANCH_NAME}}\/api'/g" _config.yml
```

Which replaces the api_url in the _config.yml with the `/api/branch_name/api` location before running a jekyll build. 

https://github.com/IIIF/api/blob/3301cb7633d8491ba3bf95cd2244656a2b32f3ff/.github/workflows/preview.yml#L39

**Comment by glenrobson** [comment]
But this isn't going to work for the ci test (which are currently disabled). That builds the website into `_site/test` directory to check the links don't assume that it runs on the root part of the website. A new _config could be created in the Rakefile that updates a the `site.api-url` to `/test/api`.

An alternative that would be really useful is if we could define the api as:

```
api_url:        '{{ site.baseurl }} /api'
```

As we can set the base url when building the jekyll site:
```
jekyll "build -d _site/test --baseurl /test"
```

@mnyrop do you have any suggestions? The only solution I can think of is to have a `_config.yml` for the ci tests. E.g. _config-ci.yml.

**Comment by glenrobson** [comment]
```
rake preview <branch_name>
```
# Ci 
either rake task or 2 configs (config could be dynamic)

**Comment by mnyrop** [comment]
@glenrobson @hadro i'm bumping this conversation over to #20; current issue can remain as a content migration / link implementation ticket.

i'll add this work in an api branch `chore/wireframe-preview-ci` for testing and will move the rake tasks over to the theme gem afterwards.
