### ISSUE TITLE
Sanity check for later: find way to check internal links for correct API variables

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#33]
E.g., we will need to make sure all things that reference API versions as variables are working correctly, like this one:

`{{ site.url }}{{ site.baseurl }}/api/presentation/3.{{ site.presentation_api.draft.minor }}/#language-of-property-values`

needs to get converted to something like this: 
`{{ site.api_url }}/presentation/{{site.data.apis.presentation.latest.major}}.{{ site.data.apis.presentation.latest.minor }}/#language-of-property-values`

Internal link checker in CI may already cover this, just documenting here to make sure before I forget.

**Comment by mnyrop** [comment]
@hadro i can also use Atom's native `grep` to look for `{{ site.url }}{{ site.baseurl }}` and `{{ site.url }}{{ site.baseurl }}/api`. feel free to @ me if that would be useful.

**Comment by hadro** [comment]
Yeah, sublime text has the same thing, that was my intent, but will ping you if I get myself into trouble...
