### ISSUE TITLE
Implement theme gem on Cookbook sites

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#37]
- Cookbook
- Guides
- Fixtures
- Registry
- Training (much harder, maybe not possible)

**Comment by glenrobson** [comment]
Cookbook theme application notes:
 * What to do with all.md? 
   * https://preview.iiif.io/cookbook/wireframe/recipe/all/
   * Remove? 
   * Link from front page? 
   * Menu option below hero image? 
   * Previously this was linked from every recipe. e.g. https://iiif.io/api/cookbook/recipe/0001-mvm-image/
 * Style of recipes all.md - remove pullet point and format.

 * Formatting issue with numbers in JSON examples. CSS class `number` adds white background and padding.
    * For example: https://preview.iiif.io/cookbook/wireframe/recipe/0005-image-service/ in this case the styling of the numbers also pushes off the highlight. 
 * Need to format back ticked words. It looks OK on the API site but a bit strange in the cookbook for example in Implementation Notes in https://preview.iiif.io/cookbook/wireframe/recipe/0001-mvm-image/ - "The JSON-LD opens with the `@context` declaration" which gives the following HTML:
`
The JSON-LD opens with the <code class=" highlighter-rouge language-plaintext">@context</code> declaration
`

 * How do I set the hero image for all recipes? I tried in the layout [recipe.md](https://github.com/IIIF/cookbook-recipes/blob/wireframe/_layouts/recipe.md)
 * Can I give a credit for the hero image?: https://www.si.edu/object/archives/components/sova-nmah-ac-0396-ref38

**Comment by hadro** [comment]
>     * What to do with all.md?

Let's discuss in our 1-on-1 tomorrow -- I'm not sure that we need the duplication of all.md, which covers the same thing on the homepage, no? 

> * Can I give a credit for the hero image?: https://www.si.edu/object/archives/components/sova-nmah-ac-0396-ref38

For the credit line, I'd just add something at the bottom of the page, I'd rather not overcomplicate it.

**Comment by glenrobson** [comment]
I think all of the style issues are fixed now:

https://preview.iiif.io/cookbook/wireframe/index.html
