### ISSUE TITLE
Add third iteration of include that has text side by side

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#39]
As discussed on 7/23, instead of tabbed interface, would be useful to have two columns of text

**Comment by mnyrop** [comment]
à la [get-involved/#iiif-consortium](https://preview.iiif.io/root/wireframe/get-involved/#iiif-consortium) but with side by side text; see: [_includes/blocks/image-and-text.html](https://github.com/mnyrop/iiifc-theme/blob/main/_includes/blocks/image-and-text.html)
