### ISSUE TITLE
Line-height increased somehow?

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#43]
On the API site, I'm seeing an odd increase in the global line-height, though not sure why that would be happening.

E.g., https://preview.iiif.io/api/wireframe/image/3.0/
(Previous line-height visible here: https://preview.iiif.io/api/spec_layout_revision/api/presentation/3.0/)

<img width="894" alt="image" src="https://user-images.githubusercontent.com/81478/127083127-93603c10-06f4-4b7f-ba36-a40166770f38.png">

**Comment by mnyrop** [comment]
note to self:
```
.api-content {
    line-height: 2;
}
```
