### ISSUE TITLE
Spec layout and api-table css have changed?

### ISSUE THREAD

**Issue by hadro** [IIIF/iiifc-theme#48]
The left-padding seems off when I run the latest version of the theme locally on the API site, and the API-table has lost cell borders: 
![Screen Shot 2021-08-05 at 10 39 28 AM](https://user-images.githubusercontent.com/81478/128369528-39555978-e7b1-493c-9ce0-84b4085a8174.png)

For comparison, here's what it looks like on current preview for API:
![Screen Shot 2021-08-05 at 10 45 00 AM](https://user-images.githubusercontent.com/81478/128370071-12f234f5-9d4f-4602-9451-2a3b99245735.png)

Maybe something about the css refactor caused this? 
I'm not skilled enough to fully diagnose, but testing iterations locally looks like it was introduced in this commit: 
https://github.com/IIIF/iiifc-theme/commit/b70f5cf9d99d279502edb751c0933af18deb8c59

**Comment by mnyrop** [comment]
@hadro that sure looks like culprit. i'll patch it now.
